---
# roles/virtualhost_role/tasks/main.yml

- name: "Include version-specific variables for OS."
  include_vars: "{{ specific_variables }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_version }}.yml"
        - "vars/{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_distribution|lower }}.yml"
        - "vars/{{ ansible_os_family|lower }}.yml"
      loop_control: loop_var=specific_variables
      skip: true

- name: "Include OS specific tasks"
  include_tasks: "{{ specific_tasks }}"
  with_first_found:
    - files:
        - "tasks/{{ ansible_distribution|lower }}_{{ ansible_distribution_version }}.yml"
        - "tasks/{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yml"
        - "tasks/{{ ansible_distribution|lower }}.yml"
        - "tasks/{{ ansible_os_family|lower }}.yml"
      loop_control: loop_var=specific_tasks
      skip: true

- name: "Set virtualhost facts"
  set_fact:
    virtualhost_role_fact_http_port: virtualhost_role_http_port
    virtualhost_role_fact_https_port: virtualhost_role_https_port
    virtualhost_role_fact_secure: virtualhost_role_https_port is defined and ssl_role_fact_use_ssl is defined
    virtualhost_role_fact_document_root: virtualhost_role_document_root

- name: "Setup virtualhost"
  when: ssl_role_stat_key.stat.exists and ssl_role_stat_crt.stat.exists
  block:
    - name: "Copy reverse-proxy http virtualhost configuration"
      when: virtualhost_role_fact_secure == false
      become: true
      template:
        src: vhost.conf.j2
        dest: "/etc/apache2/sites-available/{{ inventory_hostname }}.conf"
        backup: true
        owner: root
        group: root
        mode: u=rw

    - name: "Copy reverse-proxy redirect to http-2-https virtualhost"
      when: virtualhost_role_fact_secure
      become: true
      template:
        src: vhost-redirect.conf.j2
        dest: "/etc/apache2/sites-available/{{ inventory_hostname }}.conf"
        backup: true
        owner: root
        group: root
        mode: u=rw

    - name: "Enable site {{ inventory_hostname }}"
      become: true
      command: "a2ensite {{ inventory_hostname }}.conf"

    - name: "Copy virtualhost for reverse-proxy with SSL"
      when: virtualhost_role_fact_secure
      become: true
      template:
        src: vhost-ssl.conf.j2
        dest: "/etc/apache2/sites-available/{{ inventory_hostname }}-ssl.conf"
        backup: true
        owner: root
        group: root
        mode: u=rw

    - name: "Enable site {{ inventory_hostname }}"
      become: true
      when: virtualhost_role_fact_secure
      command: "a2ensite {{ inventory_hostname }}.conf"
  rescue:
    - debug: msg="Could not copy virtualhost configuration file(s)."
  always:
    - debug: msg="Virtualhost(s) for reverse-proxy configured successfully."
      notify: restart apache2