---
# roles/virtualhost_role/tasks/debug-group-and-host-vars.yml

# Debug group_vars and host_vars values

- name: "Debug - group and host vars from {{ hostvars[inventory_hostname] }}"
  debug: msg="{{ hostvars[inventory_hostname] }}"
  when: virtualhost_role_debug
